# Generated by Django 3.0.8 on 2020-07-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='CHAKRABORTY FAMILY BLOG', max_length=255),
        ),
    ]
